### ISSUE TITLE
Exception while filtering logs

### ISSUE THREAD

**Issue by dazza5000** [fatangare/LogcatViewer#6]
Fatal Exception: java.util.ConcurrentModificationException
       at java.util.LinkedList$LinkIterator.next(LinkedList.java:124)
       at java.util.LinkedList.addAll(LinkedList.java:394)
       at java.util.LinkedList.<init>(LinkedList.java:261)
       at com.github.pedrovgs.lynx.model.Lynx.notifyNewTraces(Lynx.java:156)
       at com.github.pedrovgs.lynx.model.Lynx.access$100(Lynx.java:35)
       at com.github.pedrovgs.lynx.model.Lynx$1.onTraceRead(Lynx.java:79)
       at com.github.pedrovgs.lynx.model.Logcat.notifyListener(Logcat.java:95)
       at com.github.pedrovgs.lynx.model.Logcat.readLogcat(Logcat.java:85)
       at com.github.pedrovgs.lynx.model.Logcat.run(Logcat.java:70)

**Comment by dazza5000** [comment]
Please let me know if there are any more details you need from me. Thank you!

**Comment by dazza5000** [comment]
Wrong project. Please delete. Sorry.
