### ISSUE TITLE
Floating view not opening

### ISSUE THREAD

**Issue by lcsmoretto** [fatangare/LogcatViewer#7]
When execute `LogcatViewer.showLogcatLoggerView(getApplication().getApplicationContext());`, a notification is displayed. But when user click then, an error happens:

```
04-26 10:42:36.491 23548-23548/br.com.eyemobile.eyemobilepos W/System.err: java.lang.IllegalArgumentException: View=wei.mark.standout.ui.Window{c6e96ec V.E...... ......I. 0,0-0,0} not attached to window manager
04-26 10:42:36.491 23548-23548/br.com.eyemobile.eyemobilepos W/System.err:     at android.view.WindowManagerGlobal.findViewLocked(WindowManagerGlobal.java:451)
04-26 10:42:36.491 23548-23548/br.com.eyemobile.eyemobilepos W/System.err:     at android.view.WindowManagerGlobal.updateViewLayout(WindowManagerGlobal.java:363)
04-26 10:42:36.491 23548-23548/br.com.eyemobile.eyemobilepos W/System.err:     at android.view.WindowManagerImpl.updateViewLayout(WindowManagerImpl.java:115)
04-26 10:42:36.491 23548-23548/br.com.eyemobile.eyemobilepos W/System.err:     at wei.mark.standout.StandOutWindow.updateViewLayout(StandOutWindow.java:1766)
04-26 10:42:36.491 23548-23548/br.com.eyemobile.eyemobilepos W/System.err:     at wei.mark.standout.ui.Window.onFocus(Window.java:319)
04-26 10:42:36.491 23548-23548/br.com.eyemobile.eyemobilepos W/System.err:     at wei.mark.standout.StandOutWindow.unfocus(StandOutWindow.java:1731)
04-26 10:42:36.491 23548-23548/br.com.eyemobile.eyemobilepos W/System.err:     at wei.mark.standout.StandOutWindow.focus(StandOutWindow.java:1446)
04-26 10:42:36.491 23548-23548/br.com.eyemobile.eyemobilepos W/System.err:     at wei.mark.standout.StandOutWindow.show(StandOutWindow.java:1098)
04-26 10:42:36.491 23548-23548/br.com.eyemobile.eyemobilepos W/System.err:     at wei.mark.standout.StandOutWindow.onStartCommand(StandOutWindow.java:383)
04-26 10:42:36.491 23548-23548/br.com.eyemobile.eyemobilepos W/System.err:     at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4128)
04-26 10:42:36.491 23548-23548/br.com.eyemobile.eyemobilepos W/System.err:     at android.app.ActivityThread.access$2400(ActivityThread.java:229)
04-26 10:42:36.491 23548-23548/br.com.eyemobile.eyemobilepos W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1924)
04-26 10:42:36.491 23548-23548/br.com.eyemobile.eyemobilepos W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
04-26 10:42:36.491 23548-23548/br.com.eyemobile.eyemobilepos W/System.err:     at android.os.Looper.loop(Looper.java:148)
04-26 10:42:36.491 23548-23548/br.com.eyemobile.eyemobilepos W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:7325)
04-26 10:42:36.491 23548-23548/br.com.eyemobile.eyemobilepos W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
04-26 10:42:36.491 23548-23548/br.com.eyemobile.eyemobilepos W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
04-26 10:42:36.491 23548-23548/br.com.eyemobile.eyemobilepos W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
04-26 10:42:36.501 23548-23548/br.com.eyemobile.eyemobilepos W/System.err: java.lang.IllegalArgumentException: View=wei.mark.standout.ui.Window{c6e96ec V.E...... ......I. 0,0-0,0} not attached to window manager
04-26 10:42:36.501 2658-2731/? V/BroadcastQueue: [background] Process cur broadcast BroadcastRecord{9575ce3 u0 com.samsung.android.providers.context.log.action.USE_APP_FEATURE_SURVEY qIdx=4}, state= (APP_RECEIVE) DELIVERED for app ProcessRecord{67e909b 4223:com.samsung.android.providers.context/u0a190}
04-26 10:42:36.501 2658-2658/? V/MARsPolicyManager: handelNotificationBarClicked pkgName = br.com.eyemobile.eyemobilepos
04-26 10:42:36.501 23548-23548/br.com.eyemobile.eyemobilepos W/System.err:     at android.view.WindowManagerGlobal.findViewLocked(WindowManagerGlobal.java:451)
04-26 10:42:36.501 23548-23548/br.com.eyemobile.eyemobilepos W/System.err:     at android.view.WindowManagerGlobal.updateViewLayout(WindowManagerGlobal.java:363)
04-26 10:42:36.501 23548-23548/br.com.eyemobile.eyemobilepos W/System.err:     at android.view.WindowManagerImpl.updateViewLayout(WindowManagerImpl.java:115)
04-26 10:42:36.501 23548-23548/br.com.eyemobile.eyemobilepos W/System.err:     at wei.mark.standout.StandOutWindow.updateViewLayout(StandOutWindow.java:1766)
04-26 10:42:36.501 23548-23548/br.com.eyemobile.eyemobilepos W/System.err:     at wei.mark.standout.ui.Window.onFocus(Window.java:319)
04-26 10:42:36.501 23548-23548/br.com.eyemobile.eyemobilepos W/System.err:     at wei.mark.standout.StandOutWindow.focus(StandOutWindow.java:1449)
04-26 10:42:36.501 23548-23548/br.com.eyemobile.eyemobilepos W/System.err:     at wei.mark.standout.StandOutWindow.show(StandOutWindow.java:1098)
04-26 10:42:36.501 23548-23548/br.com.eyemobile.eyemobilepos W/System.err:     at wei.mark.standout.StandOutWindow.onStartCommand(StandOutWindow.java:383)
04-26 10:42:36.501 23548-23548/br.com.eyemobile.eyemobilepos W/System.err:     at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4128)
04-26 10:42:36.501 23548-23548/br.com.eyemobile.eyemobilepos W/System.err:     at android.app.ActivityThread.access$2400(ActivityThread.java:229)
04-26 10:42:36.501 23548-23548/br.com.eyemobile.eyemobilepos W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1924)
04-26 10:42:36.501 23548-23548/br.com.eyemobile.eyemobilepos W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
04-26 10:42:36.501 23548-23548/br.com.eyemobile.eyemobilepos W/System.err:     at android.os.Looper.loop(Looper.java:148)
04-26 10:42:36.501 23548-23548/br.com.eyemobile.eyemobilepos W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:7325)
04-26 10:42:36.501 23548-23548/br.com.eyemobile.eyemobilepos W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
04-26 10:42:36.501 23548-23548/br.com.eyemobile.eyemobilepos W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
04-26 10:42:36.501 23548-23548/br.com.eyemobile.eyemobilepos W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)


```

**Comment by cbriseno** [comment]
When executing this library on API >= 23 you have to request permission to overlay windows.

```java
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        if (!Settings.canDrawOverlays(getApplicationContext())) {
            /** if not construct intent to request permission */
            Intent intent = new Intent(Settings.ACTION_MANAGE_OVERLAY_PERMISSION,
                    Uri.parse("package:" + getPackageName()));
            /** request permission via start activity for result */
            startActivityForResult(intent, 112);
        }else{
            LogcatViewer.showLogcatLoggerView(MainActivity.this);
        }
    }

    @Override
    protected void onActivityResult(int requestCode, int resultCode,  Intent data) {
        /** check if received result code
         is equal our requested code for draw permission  */
        if (requestCode == 112) {
            if (Settings.canDrawOverlays(this)) {
                LogcatViewer.showLogcatLoggerView(MainActivity.this);
            }
        }
    }
```

**Comment by lpotherat** [comment]
Should be added to README
